[package]
name = "ranagrams"
version = "0.1.2"
authors = ["dfhoughton <dfhoughton@gmail.com>","jwmhjwmh@gmail.com"]
description= "anagram discovery tool"
homepage = "https://github.com/dfhoughton/ranagrams"
repository = "https://github.com/dfhoughton/ranagrams"
readme = "README.md"
keywords = [ "anagram", "language", "game" ]
categories = [ "games", "command-line-utilities" ]
license = "GPL-2.0"

[[bin]]
name = "rana"

[dependencies]
num_cpus = "1.6.2"
mpmc = "0.1.3" # for queue
clap = "~2.19.0"
rand = "0.3"
